# Languages
# Each language key stands as its language code
# ################################
en:
  languageName: English
  weight: 1
# Secondary language
# fr:
#   languageName: Fran√ßais
#   weight: 1
#   contentDir: content/fr