# Site Varialbes
sitename: Static is The New Dynamic
author: Bud Parr
url: https://www.thenewdynamic.org
image_url: https://thenewdynamic.imgix.net
categories:
  - 'article'
  - 'event'
title: The New Dynamic
description: "Static Site Generators <small>and the Post-CMS paradigm</small>"
type:
  - Article
  - Tutorial
  - Presentation

short_name: BPNY
display: fullscreen

# full_rebuild: true
incremental: true
port: 3575
markdown: kramdown
future: false
incremental: false
timezone: Etc/Zulu

# PRODUCTION
google_analytics_id: UA-30899180-4
bust_css_cache: true
production: true


# Structure

plugins_dir:  ./_app/_plugins
layouts_dir:  ./_app/_layouts
includes_dir: ./_app/_includes

include:
  - _pages
exclude:
  - readme.md
  - todo.md
  - license.md
  - Gemfile
  - Gemfile.lock
  - bower.json
  - CNAME
  - node_modules
  - sass
  - gulpfile.js
  - package.json
  - javascript
  - vendor
permalink: pretty

utm_parameters_links: '?utm_source=thenewdynamic.org&utm_medium=website&utm_campaign=links'
utm_parameters_showcase: '?utm_source=thenewdynamic.org&utm_medium=website&utm_campaign=showcase'
# PLUGINS
# gems: [jekyll-sitemap, jekyll-imgix]
gems:
  - jekyll-seo-tag
  - jekyll/imgix
  - jekyll-gist
  - jekyll-redirect-from
imgix:
  source: thenewdynamic.imgix.net # Your imgix source address

compress_html:
  ignore:
    envs: [development]
  profile: false


# CONTENT
collections:
  landing_pages:
    output: true
    permalink: '/:path/'
  links:
    output: false
    permalink: '/link/:path/'
    future: true
    description: 'Links to from around the web'
  meetups:
      output: false
  showcase:
    output: true
    permalink: '/:collection/:path/'
  tool:
    output: true
    permalink: '/:collection/:path/'
  tool_type:
    output: true
    permalink: '/tools/:path/'

# DEFAULTS
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      category: article
  - scope:
      path: ''
      type: events
    values:
      layout: page
  - scope:
      path: ''
      type: landing_pages
    values:
      layout: page
      feed: false
  - scope:
      path: ''
      type: tool
    values:
      layout: tool
  - scope:
      path: ''
      type: tool_type
    values:
      layout: tools
  - scope:
      path: ''
      type: staff
    values:
      layout: page
      feed: false
  - scope:
      path: ''
      type: meetups
    values:
      feed: false
  - scope:
      path: ''
      type: showcase
    values:
      layout: showcase-individual
  - scope:
      path: '_pages'
    values:
      permalink: /:basename/
