---
upload_path: "/static/images/"
frontmatter_file_url_template: "/images/"
body_file_url_template: "/images/"
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
  article:
    default_front_matter_template: article
  book:
    default_front_matter_template: book
  event:
    default_front_matter_template: event
  review:
    default_front_matter_template: review
version: '0.26'
